version: '3'

services:

    app:
        build: .
        image: docker.pkg.github.com/ondata/appaltipop.it/appaltipop-app:latest
        environment:
            - ES_SCHEME=${ES_SCHEME:-http}
            - ES_HOST=${ES_HOST:-es01}
            - ES_PORT=${ES_PORT:-9200}
            - ES_INDEX_PREFIX=${ES_INDEX_PREFIX:-appaltipop}

    proxy:
        build: proxy/
        image: docker.pkg.github.com/ondata/appaltipop.it/appaltipop-proxy:latest
        environment:
            - APP_URL=${APP_URL:-http://app:3000}
            - OAS_URL=${OAS_URL:-http://oas-ui-v1:8080}
        ports:
            - ${PROD_PORT:-8080}:80
        depends_on:
            - app
            - oas-ui-v1

    oas-ui-v1:
        build: oas/
        image: docker.pkg.github.com/ondata/appaltipop.it/appaltipop-oas:latest

    es01:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
        container_name: appaltipop-es01
        environment:
            - discovery.type=single-node
            - cluster.name=appaltipop
        ports:
            - 9200:9200

    kibana:
        image: docker.elastic.co/kibana/kibana:7.9.2
        container_name: appaltipop-kibana
        environment:
            SERVER_NAME: dashboard.appaltipop.it
            ELASTICSEARCH_HOSTS: http://es01:9200
        ports:
            - 5601:5601
